services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_data:/qdrant/storage
